import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'white',
    },
    TextInputContainer:{
      width: '30%'
    },
    inputText: {
      height: 50,
      fontSize: 18,
      fontFamily: 'Pretendard-Regular',
      borderWidth: 1,
      borderColor: 'black',
      marginBottom: 24,
      borderRadius: 10,
      backgroundColor: '#D9D9D9',
      color: "#696969",
      paddingHorizontal: 12,
      justifyContent:"center",
      alignItems:'center'
    },
    subButtonGroup:{
      justifyContent: 'center',
      flexDirection: 'row',
    },
    subButton: {
      justifyContent: 'center',
      paddingHorizontal:15,
      height: 30,
      marginHorizontal: 10,
    },
    subButtonText: {
      justifyContent: 'center',
      fontFamily: 'Pretendard-Regular',
      fontSize: 15,
    },
    JoinContent:{
      width:"45%",
      flexDirection:'row',
      justifyContent:'space-between', 
      alignItems:'center',
      //borderWidth: 2,
      marginBottom:24,
    },
    DropDownButton:{
      flex: 1,
      height: 50,
      backgroundColor: '#D9D9D9',
      borderRadius: 10,
      borderWidth: 1,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 12,
    },
    DropDownItem:{
      width:'100%',
      justifyContent:'center',
      alignItems:'center',
      paddingVertical: 8,
    },
    DropdownMenu:{
      borderRadius: 10,
      backgroundColor:'#D9D9D9',  
    },
    HeaderContainer:{
      justifyContent: 'space-between',
      alignItems: 'center',
      flexDirection: 'row',
      height: 85,
      backgroundColor: 'white',
      elevation: 10,
      paddingHorizontal: 24,
    },
    HeaderTitleText:{
      fontSize: 34,
      fontFamily: 'Pretendard-SemiBold',
      color: 'black',
      alignSelf:'center',
    },
    SearchContainer:{
      alignItems: 'flex-end',
      flexDirection: 'row',
    },
    searchInputText:{
      width: 408,
      height: 46,
      borderWidth: 2,
      borderRadius: 10,
      backgroundColor: '#F6F6F6',
      paddingHorizontal: 15,
      fontSize: 18,
      fontFamily: 'Pretendard-Regular',
    },
    SearchButton: {
      justifyContent: 'center',
      alignItems: 'flex-end',
      marginHorizontal: 10,
    },
    MyPageButton: {
      alignItems: 'center',
      alignSelf: 'flex-end'
    },
    BodyContainer:{
      flex:1,
      flexDirection: 'row',
      justifyContent: 'center',
      paddingVertical:30,
      paddingHorizontal: 40,
    },
    RecentKeywordContainer:{
      flex: 1,
    },
    RecentKeywordNode:{
      borderColor: 'Black',
      borderWidth: 2,
      borderRadius: 12,
      justifyContent:'space-between',
      alignItems:'center',
      flexDirection:'row',
      marginBottom: 12, 
      paddingHorizontal: 24,
      paddingVertical: 6,
    },
    RecentKeywordTextContainer:{
      flex: 1,
    },
    RecentKeywordText:{
      fontFamily: 'Pretendard-Regular',
      fontSize: 18,
      marginVertical: 12,
      color: 'black'
    },
    RecentkeywordDeleteButton: {
      padding: 10,
    },
    SearchResultProductContainer:{
      flex: 0.5,
      justifyContent: 'center',
      flexDirection: 'column',
    },
    SearchResultProductNode: {
      height: 200,
      borderWidth: 1,
      borderRadius: 20,
      paddingHorizontal: 18,
      paddingVertical: 12,
      flexDirection: 'row',
      marginBottom: 24,
      backgroundColor: 'white',
    },    
    SearchResultProductImage: {
      flex: 1,
      borderRadius: 20,
      backgroundColor: 'white',
      marginRight: 24,
    },
    SRProductDetailContainer:{
      flex:3,
      justifyContent:'flex-start',
      flexDirection:'column',
      paddingVertical: 12,
    },
    SRProductDetailText:{
      fontFamily: 'Pretendard-Regular',
      fontSize: 25,
      color: 'black',
      alignSelf: 'flex-start',
      marginBottom: 10,
    },
    ProductDetailScrollContainer:{
      width: '100%',
      borderWidth: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingBottom: 50,
    },
    ProductMainInfoContainer:{
      alignItems:'center',
      width: '100%', 
    },
    ImageContainer:{
      borderWidth: 2,
      borderRadius: 20,
      justifyContent:'center',
      alignItems:'center',
      width: '20%',
      height: 300,
      marginBottom: 24,
    },
    ProductMainImage:{
      borderRadius: 20,
      width: "100%",
      height: "100%",
      resizeMode: 'cover',
    },
    ProductSubInfoContainer:{
      justifyContent:'center',
      alignItems: 'center',
      width: '100%',
    },
    ProductSubInfoMenuContainer:{
      width: '50%',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexDirection:'row',
      marginBottom: 24,
    },
    ProductSubInfoMenuNodeContainer:{
      borderWidth: 2,
      borderRadius: 20,
      alignItems:'center',
      justifyContent:'center',
      flex: 1,
      marginHorizontal: 12,
    },
    ProductSubInfoMenuNodeContainer_pressed:{
      borderWidth: 2,
      borderRadius: 20,
      alignItems:'center',
      justifyContent:'center',
      flex: 1,
      marginHorizontal: 12,
      backgroundColor: '#696969',
    },
    ProductSubInfoMenuText:{
      paddingVertical: 6,
      fontSize: 24,
      fontFamily: 'Pretendard-Regular',
      color: 'black'
    },
    ProductSubInfoMenuText_pressed:{
      paddingVertical: 6,
      fontSize: 24,
      fontFamily: 'Pretendard-Regular',
      color: 'white'
    },
    ProductDetailImage:{
      //flex: 1,
      width: '50%',
      height: 700,
      //resizeMode:'contain',
    },
    ProductText:{
      fontSize: 18,
      fontFamily: 'Pretendard-Regular',
      color: 'black',
      marginBottom: 12,
    },
    ProductBottomButtonsContainer:{
      width:'50%',
      justifyContent: 'space-between',
      alignItems:'center',
      alignSelf:'center', 
      flexDirection: 'row', 
      backgroundColor: 'white',
      elevation: 20,
      borderTopStartRadius:20,borderTopEndRadius:20,
      borderWidth: 2,
    },
    ProductBottomButton:{
      flex:1,
      //borderWidth: 2,
      justifyContent: 'center',
      alignItems:'center',
    },
    ProductBottomButtonText:{
      fontFamily: 'Pretendard-Regular',
      fontSize: 24,
      paddingVertical: 12,
      color: 'black',
    },
    ProductLocationModalContainer:{
      flex:1,
      justifyContent: 'center',
      alignItems:'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    ProductLocationModalContent:{
      width: '50%',
      height: '80%',
      backgroundColor:'white',
      borderWidth: 2,
      borderRadius: 20,
      justifyContent: 'flex-start',
      padding:42,
    },
    ProductLocationModalContentHeader:{
      width: "100%",
      height: 40,
      flexDirection:'row',
      justifyContent:'space-between',
      alignItems:'center',
      marginBottom: 24,
    },
    ProductLocationModalMapContainter:{
      flex: 1,
      borderWidth:2,
    },
    AddCartModalContainer:{
      flex:1,
      justifyContent:'flex-end',
      alignItems:'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    AddCartModalContent:{
      width:'30%',
      height:248,
      justifyContent:'space-between',
      alignItems:'center',
      backgroundColor:'white',
      borderWidth: 1,
      borderTopLeftRadius:20,
      borderTopRightRadius:20,
      paddingHorizontal:24,
      paddingVertical:12,
    },
    ModalIconContainer:{
      marginHorizontal: 12,
    },
    AddCartButton:{
      justifyContent: 'center',
      alignItems:'center',
      backgroundColor:'#9AB4F5',
      borderRadius: 15,
      paddingVertical: 8,
      paddingHorizontal: 24,
      alignSelf: 'flex-end'
    },
    MyPageMenuContainer:{
      width: '50%',
      borderWidth: 1  ,
      borderRadius: 20,
      flexDirection: 'row',
      justifyContent: 'flex-start',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingVertical: 28,
      marginBottom: 16,
      backgroundColor: 'white',
      //elevation:10
    },
    MainText: {
      fontFamily: 'Pretendard-Regular',
      fontSize: 24,
      color: 'black',
    },
    RecommendProductListContainer:{
      flexDirection: 'row',
    },
    MyPageMenuIconContainer:{
      width: 25, 
      height: 25, 
      marginRight: 12
    },
    MyPageMenuIcon:{
      width: '100%', 
      height: '100%'
    },
    RecentProductContainer:{
      //borderWidth:2,
      width: 150,
      height: 244,
      marginRight: 12
    },
    RecentProductImage:{
      width: '100%',
      height: 188,
      borderRadius: 20,
      marginBottom: 8.5,
    },
    SemiBoldText:{
      fontFamily: 'Pretendard-SemiBold',
      color: 'black',
    },
    OrderContainer:{
      width: '50%',
      borderWidth:1,
      borderRadius: 20,
      marginBottom: 24,
      paddingHorizontal:24,
      paddingVertical:12,
    },
    OrderSubContainer:{
      width: '100%',
      paddingVertical:12,
      justifyContent: 'flex-start',
      alignItems:'flex-start',
      //borderWidth:1,
    },
    OrderProductImageContainer:{
      width: 100,
      height: 125,
      marginRight: 12,
      borderRadius: 20,
      borderWidth: 1,
      backgroundColor:'#FFE68C'
    },
    OrderProductImage:{
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
      borderRadius: 20,
    },
    OrderListPNameContainer:{
      width:'100%',
      justifyContent:'center',
      marginBottom: 24,
      //borderWidth:2,
    },
    OrderProductQuantityText:{
      fontFamily:'Pretendard-Light',
      color:'#696969',
      fontSize: 14,
    },
    OrderTotalContainer:{
      width:'100%',
      //borderWidth: 2,
      paddingHorizontal: 12,
    },
    OrderTotalContent:{
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems:"center",
      marginBottom: 12,
    },
    LightText:{
      fontFamily:'Pretendard-Light',
      color: 'black',
      fontSize: 18,
    },
    OrderListButton:{
      width: '100%',
      height: 52,
      justifyContent: 'center',
      alignItems:'center',
      borderRadius: 14,
      borderWidth: 1,
      backgroundColor: '#757575'
    },
    MediumText:{
      fontFamily:'Pretendard-Medium',
      color: 'black',
    },
    ModifyPagePasswordInputContainer:{
      width: "50%",
      borderWidth: 1,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems:'flex-start',
      paddingVertical: 24,
      paddingHorizontal: 24,
      marginBottom: 36,
    },
    ModifyPagePasswordInputContent:{
      width: "100%",
      //borderWidth: 1,
      paddingVertical: 12,
    },
    ModifyInfoInputContainer:{
      width: "50%",
      borderWidth: 1,
      borderRadius: 20,
      justifyContent: 'center',
      alignItems:'flex-start',
      paddingVertical: 12,
      marginBottom: 12,
    },
    ModifyInfoInputContent:{
      width: "100%",
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems:'center',
      paddingHorizontal: 36,
      paddingVertical: 12,
    },
    ModifyInfoButtonContainer:{
      width: "50%",
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems:'center',
      paddingVertical: 24,
    },
    ModifyInfoCancelButton:{
      width: 200,
      height: 48,
      justifyContent: 'center',
      alignItems:'center',
      backgroundColor:'#FFB0B0',
      paddingHorizontal: 32,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
    },
    WarningModalContent:{
      elevation: 20,
      width: '30%',
      backgroundColor: 'white',
      borderRadius: 20,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 36,
      paddingHorizontal: 24,
    },
    WaringModalButton:{
      justifyContent: 'center',
      alignItems:'center',
      paddingVertical: 8,
      paddingHorizontal: 24,
      backgroundColor:'white',
      borderRadius: 12,
      borderWidth: 1,
      marginTop: 12,

    }
  });

  export default styles;
  